spring:
  application:
    name: vestory

  datasource:
    url: jdbc:postgresql://localhost:5432/vestory
    username: vestory
    password: vestory

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

vestory:
  jwt:
    issuer: vestory
    secret: ${JWT_SECRET}
    access-token-ttl: 15m
    refresh-token-ttl: 30d

twelve-data:
  api-key: ${TWELVE_DATA_API_KEY}
  base-url: https://api.twelvedata.com

fmp:
  api-key: ${FMP_DATA_API_KEY}
  base-url: https://financialmodelingprep.com/stable