spring:
  application:
    name: vestory

  datasource:
    url: jdbc:postgresql://localhost:5433/vestory
    username: vestory
    password: vestory

  jpa:
    hibernate:
      ddl-auto: update

twelve-data:
  api-key: ${TWELVE_DATA_API_KEY}
  base-url: https://api.twelvedata.com

