spring:
  application:
    name: vestory

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/vestory}
    username: ${DB_USERNAME:vestory}
    password: ${DB_PASSWORD:vestory}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

vestory:
  jwt:
    issuer: vestory
    secret: ${JWT_SECRET}
    access-token-ttl: 15m
    refresh-token-ttl: 30d

twelve-data:
  api-key: ${TWELVE_DATA_API_KEY}
  base-url: https://api.twelvedata.com

fmp:
  api-key: ${FMP_DATA_API_KEY}
  base-url: https://financialmodelingprep.com/stable
